movies = [{"naslov":"Mr. Denning Drives North","redatelj":"Falkner Elbourne","godina":2006,"zanr":"Crime|Drama|Mystery"},
{"naslov":"Lonely Guy, The","redatelj":"Rey Daymond","godina":1998,"zanr":"Comedy"},
{"naslov":"Upstairs and Downstairs","redatelj":"Florry Scawen","godina":1985,"zanr":"Comedy"},
{"naslov":"Duel at Diablo","redatelj":"Florina Ostler","godina":2010,"zanr":"War"},
{"naslov":"Genghis Khan","redatelj":"Madelin Steer","godina":2008,"zanr":"Adventure|Drama|War"},
{"naslov":"Children Who Chase Lost Voices from Deep Below (Hoshi o ou kodomo) (Journey to Agartha)","redatelj":"Minnaminnie Giovanazzi","godina":2010,"zanr":"Animation|Drama|Fantasy"},
{"naslov":"Joneses, The","redatelj":"Sholom Mahedy","godina":2004,"zanr":"Comedy|Drama"},
{"naslov":"Gurren Lagann: The Lights in the Sky are Stars (Gekijô ban Tengen toppa guren ragan: Ragan hen)","redatelj":"Carson Crown","godina":1989,"zanr":"Adventure|Animation|Drama|Sci-Fi|War"},
{"naslov":"Tulsa","redatelj":"Colline Danilovich","godina":1995,"zanr":"Action|Drama|Romance"},
{"naslov":"Nothing to Lose","redatelj":"Eal Oppery","godina":2005,"zanr":"Action|Crime|Drama"},
{"naslov":"Devil's Eye, The (Djävulens öga)","redatelj":"Glendon Ghent","godina":2001,"zanr":"Comedy|Drama|Fantasy"},
{"naslov":"Flight of the Red Balloon (Voyage du ballon rouge, Le)","redatelj":"Pansie Hember","godina":1994,"zanr":"Drama"},
{"naslov":"I Will Buy You (Anata kaimasu)","redatelj":"Waldo Cafferty","godina":2005,"zanr":"Drama"},
{"naslov":"Maybe Baby","redatelj":"Selestina Schultes","godina":2007,"zanr":"Comedy|Romance"},
{"naslov":"Hell Up in Harlem","redatelj":"Francine Grandin","godina":1994,"zanr":"Crime"},
{"naslov":"That Man from Rio","redatelj":"Celinka Teissier","godina":1986,"zanr":"Action|Adventure|Comedy|Romance"},
{"naslov":"Dimensions of Dialogue (Moznosti dialogu)","redatelj":"Floyd Troni","godina":2006,"zanr":"Animation|Comedy|Fantasy"},
{"naslov":"Hellbound: Hellraiser II","redatelj":"Shawn Kincade","godina":2008,"zanr":"Horror"},
{"naslov":"Roberta","redatelj":"Lindsey Gobeaux","godina":1993,"zanr":"Comedy|Musical|Romance"},
{"naslov":"Candyman","redatelj":"Barron Klemt","godina":2004,"zanr":"Horror|Thriller"},
{"naslov":"Some Like It Hot","redatelj":"Elysee Tunney","godina":2002,"zanr":"Comedy|Crime"},
{"naslov":"Harder They Fall, The","redatelj":"Clare Thurlbourne","godina":2012,"zanr":"Drama|Film-Noir"},
{"naslov":"Deranged","redatelj":"Hilly Bunhill","godina":2008,"zanr":"Horror|Thriller"},
{"naslov":"Love Stinks","redatelj":"Marley Dobinson","godina":2004,"zanr":"Comedy"},
{"naslov":"Air Hawks","redatelj":"Peirce Gudde","godina":1998,"zanr":"Action|Drama|Mystery|Romance|Sci-Fi"},
{"naslov":"Charles Bradley: Soul of America","redatelj":"Conchita M'Barron","godina":2008,"zanr":"Documentary"},
{"naslov":"Babylon A.D.","redatelj":"Perle Banasevich","godina":1997,"zanr":"Action|Adventure|Sci-Fi|Thriller"},
{"naslov":"Battle of the Bulge","redatelj":"Jereme Rimbault","godina":2008,"zanr":"Action|Drama|War"},
{"naslov":"Stepford Wives, The","redatelj":"Orelle Wegenen","godina":1992,"zanr":"Mystery|Sci-Fi|Thriller"},
{"naslov":"Remorques (Stormy Waters)","redatelj":"Hubey Stamp","godina":1993,"zanr":"Action|Drama|Romance"},
{"naslov":"Chuck & Buck","redatelj":"Sara Durnian","godina":2008,"zanr":"Comedy|Drama"},
{"naslov":"Eye, The","redatelj":"Morty McKinless","godina":2000,"zanr":"Drama|Horror|Thriller"},
{"naslov":"Five, The (Gonin)","redatelj":"Maitilde Ruxton","godina":2010,"zanr":"Action|Crime|Drama"},
{"naslov":"Oh! What a Lovely War","redatelj":"Desmond Stagg","godina":1994,"zanr":"Musical|War"},
{"naslov":"Dr. Goldfoot and the Girl Bombs (Le spie vengono dal semifreddo)","redatelj":"Mair Burree","godina":2009,"zanr":"Comedy|Sci-Fi"},
{"naslov":"Frozen Hell (Jäämarssi) ","redatelj":"Ninnetta Bagg","godina":2002,"zanr":"Documentary|War"},
{"naslov":"Mad City","redatelj":"Juliet Imlin","godina":2009,"zanr":"Action|Drama"},
{"naslov":"Emo Philips Live","redatelj":"Ronni Kennler","godina":2009,"zanr":"Comedy"},
{"naslov":"Wuthering Heights","redatelj":"Kirsten Pitway","godina":2013,"zanr":"Drama|Romance"},
{"naslov":"Paziraie Sadeh","redatelj":"Reena Killough","godina":1998,"zanr":"Drama"},
{"naslov":"Evil of Frankenstein, The","redatelj":"Corabella Billitteri","godina":2004,"zanr":"Horror"},
{"naslov":"Ed's Next Move","redatelj":"Carney Thaxton","godina":2006,"zanr":"Comedy|Romance"},
{"naslov":"Fire-Eater (Tulennielijä)","redatelj":"Johann Meert","godina":2009,"zanr":"Drama"},
{"naslov":"Cooperstown","redatelj":"Melesa Lafontaine","godina":1979,"zanr":"Drama"},
{"naslov":"The Prisoner","redatelj":"Nollie Godmer","godina":1999,"zanr":"Drama"},
{"naslov":"Ca$h","redatelj":"Sybyl Cleaton","godina":1992,"zanr":"Crime|Thriller"},
{"naslov":"Superman III","redatelj":"Morten Bashford","godina":2007,"zanr":"Action|Adventure|Sci-Fi"},
{"naslov":"I'm King Kong!: The Exploits of Merian C. Cooper ","redatelj":"Erna Figliovanni","godina":1991,"zanr":"Documentary"},
{"naslov":"Taira Clan Saga, The (Shin heike monogatari)","redatelj":"Shari Clowney","godina":2011,"zanr":"Drama"},
{"naslov":"Once in a Lifetime: The Extraordinary Story of the New York Cosmos","redatelj":"Skipper Kettlesing","godina":2012,"zanr":"Documentary"}]
